### ISSUE TITLE
Errors ignored in cli interface for set pin code.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#103]
**Describe the bug**
set pin code leaks an expliciit msg for errors:
https://github.com/skycoin/hardware-wallet-go/blob/f99ba4d1526dd6cf38793c32dadc758fce830f56/src/cli/set_pin_code.go#L39-L47

**Environment information:**

- OS: Any
- Platform: Any
- Firmware develop

**Steps to Reproduce**
1. `go run cmd/cli/cli.go setPinCode`
2. set a pin
3. set a pin again but different from the one in step 2
4. See as the command promp end with out any error

**Actual behavior**
dies silently in case of error

**Expected behavior**
Should infor about errors if any

**Possible implementation**
Just handle posible errors from here:
https://github.com/skycoin/hardware-wallet-go/blob/f99ba4d1526dd6cf38793c32dadc758fce830f56/src/cli/set_pin_code.go#L39

**Comment by therealssj** [comment]
https://github.com/skycoin/hardware-wallet-go/blob/f99ba4d1526dd6cf38793c32dadc758fce830f56/src/cli/set_pin_code.go#L42
handle it here imo just like the rest of the functions. add a switch case for success or failure msg
