### ISSUE TITLE
Add a field for version information in get features msg

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#108]
**Is your feature request related to a problem? Please describe.**
Integrate [this change](https://github.com/skycoin/hardware-wallet-protob/pull/39) after merged.

**Describe the solution you'd like**
Just update protob related files.

**Describe alternatives you've considered**
Just this

**Comment by stdevAlDen** [comment]
@olemis consider closing this pls as the pr is merged

**Comment by olemis** [comment]
> @olemis consider closing this pls as the pr is merged

@stdevAlDen en what PR ?

**Comment by olemis** [comment]
if this feature is already implemented I'll close the issue anyways , just let me know .
