### ISSUE TITLE
Support Asynchronous User Input

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet-go#11]
Some of the wallet features require user interaction (input pincode or a mnemonic word for instance). This golang cli tool uses `fmt.Scanln` to prompt user for the desired input.

```go
./cli/device_address_gen.go:				fmt.Scanln(&pinEnc)
./cli/emulator_address_gen.go:				fmt.Scanln(&pinEnc)
./cli/device_set_pin_code.go:				fmt.Scanln(&pinEnc)
./cli/emulator_set_pin_code.go:				fmt.Scanln(&pinEnc)
```

The `fmt.Scanln` interrupts the program awaiting for user input, which is ok as long as the CLI tools is just used as a CLI.
But if someday we want to integrate it in an other software with user interface, it could be interesting to use golang "[channels](https://tour.golang.org/concurrency/2)" to awake the code when the user has finished his input.

The functions would return the channel in which they expect the user interaction to arrive and it is the responsibility of the calling code to send the desired input.

**Comment by therealssj** [comment]
the api call to the hardware wallet is a blocking operation
whats the point of this?
