### ISSUE TITLE
CLI deviceType not detected if set at the end

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-go#137]
**Describe the bug**
CLI arg `deviceType` not always detected

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.4.0 x86_64
- Firmware Version: any

**Steps to Reproduce**

Execute following from command line terminal window

```sh
$ skycoin-hw-cli recovery --usePassphrase false --wordCount 12 --deviceType USB
```

Command can be anything, failure still happens as long as `--deviceType` is preceded by other arguments

**Actual behavior**

Error message

```
[2019-06-02T02:12:25-04:00] ERROR [device-wallet]: device type not set, valid options are USB or EMULATOR
```

**Expected behavior**
Command should be executed and messages sent to Skywallet device.

**Additional context**

It works if executed like this 

```
$ skycoin-hw-cli recovery --deviceType USB --usePassphrase false --wordCount 12
```

**Possible implementation**
TBD

**Comment by therealssj** [comment]
@olemis the correct command is `skycoin-hw-cli recovery --usePassphrase --wordCount 12 --deviceType EMULATOR`

**Comment by olemis** [comment]
@therealssj I am using the USB device , not EMULATOR

**Comment by therealssj** [comment]
@olemis irrelevant. the issue is what i pointed out

**Comment by olemis** [comment]
> if you want to use `--usePassphrase true` I can convert it to a string

It should be a string because its meaning should be:

- `true` : Force passphrase
- `false` : Ignore passphrase
- no set : Do whatever is configured in device (i.e. value returned by `GetFeatures`)
