### ISSUE TITLE
Fix automatic handling of out of band success

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#148]
**Describe the bug**
Some times the device ask for external entropy and some messages are exchanged and cand get conflict with other messages, [for example](https://github.com/skycoin/hardware-wallet/issues/319#issuecomment-514153751).

**Environment information:**

- Any

**Steps to Reproduce**

1. Run long (in time, high duration) commands, for example [trng](https://github.com/skycoin/hardware-wallet#validate-the-trng).

**Actual behavior**
The messages collide

**Expected behavior**
Just work without message collision.

**Comment by jdknives** [comment]
Please fix this PR. @RomanMilishchuk nonetheless reported, that the PR helps with the issue. @stdevAlDen
