### ISSUE TITLE
Check out how static code analizer is working in Travis.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#22]
`make check` and `make lint` give me a lot of errors in my system(Linux hostname 4.19.0-1-amd64 1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux), but these are not being reported from Travis CI.

**Comment by stdevHan** [comment]
@stdevAlDen Could you put what errors are you giving?

**Comment by stdevAlDen** [comment]
> @stdevAlDen Could you put what errors are you giving?

@stdevHan this look deprecate(actually works in my laptop).
