### ISSUE TITLE
Missing return on functions

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#39]
Some functions are just logging the response instead of returning it

Example:
https://github.com/skycoin/hardware-wallet-go/blob/master/device-wallet/device-wallet.go#L258
https://github.com/skycoin/hardware-wallet-go/blob/master/device-wallet/device-wallet.go#L346
and a few others

They should return the `Success` or `Failure` message along with logging it

**Comment by olemis** [comment]
I think this is related to #11 . Mnemonic generation can be a time consuming process . I think It might be better to do implement this as an async operation .

**Comment by olemis** [comment]
In the case of `cancel` maybe there's a case for returning messages.
