### ISSUE TITLE
Set user host device entropy to the hardware-wallet to be combined with internal hw entropy.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#46]
**Feature description**
Combine internal hw device entropy with the host one.

**Is your feature request related to a problem? Please describe.**
Related to https://github.com/skycoin/hardware-wallet/issues/88

**Describe the solution you'd like**
Send entropy to the device before call `GenerateMnemonic`.

**Describe alternatives you've considered**
Other alternative could be request entropy from the device, but as the protocol implementation is not working with a call/call_back scheme this can make ugly the implementation.

**Comment by olemis** [comment]
@stdevAlDen the right approach seems to be be to send `EntropyAck` message . It would include the external entropy buffer .

https://github.com/skycoin/hardware-wallet/blob/39229d610a4f8d68d9f4f30921fd9667ea52b4b7/tiny-firmware/firmware/fsm.c#L681-L688

**Comment by olemis** [comment]
The command in the go library should receive buffer length and generate the random data e.g.

```go
func main() {
  buf := make([]byte, 32)
  _, err := io.ReadFull(rand.Reader, buf) // system secure random number generator
  if err != nil {
    log.Panic(err)
  }
  // Now we have 32 bytes of CSPRNG-generated data, give it to the hardware wallet
}
```

**Comment by stdevAlDen** [comment]
@olemis Can you check [out this](https://travis-ci.org/simelo/skycoin-hardware-wallet-go/jobs/498897216#L676), did you face any [travis issue](https://github.com/simelo/skycoin-hardware-wallet-go/blob/d4e194229a73f2baa93a3248df50a4367a969585/device-wallet/messages/messages.pb.go#L570) before?

**Comment by gz-c** [comment]
The entropy should be sourced using `cipher.RandByte`
