### ISSUE TITLE
Check message signature response

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#51]
**Describe the bug**
Look at the `messages.MessageType_MessageType_` to checkout if check message signature was success.

**Environment information:**

- Any

**Steps to Reproduce**
Just check out the "parent" issue [here](https://github.com/skycoin/hardware-wallet/issues/96).

**Actual behavior**
Ignore the result from `SkycoinCheckMessageSignature` response.

**Expected behavior**
Check the result from `SkycoinCheckMessageSignature` response.

**Possible implementation**
Just look at the `msg.Kind` in response.

**Comment by olemis** [comment]
superseded by #77
