### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#53]
**Feature description**
- [x]  A library that is a direct wrapper around hardware wallet operations
- [x] Use proto definitions from a git submodule
- [x] Add an interface so the api can be mocked
- [x] Change project structure to follow standard layout

**Related PRs**
https://github.com/skycoin/hardware-wallet-go/issues/52
https://github.com/skycoin/hardware-wallet-go/issues/39

**Comment by olemis** [comment]
@therealssj there is an open issue #52 for using protobuf from submodule and a PR #55 is aimed at fixing it .

**Comment by therealssj** [comment]
@olemis okay. I marked it as done. 
I am just using this issue to keep track of refactoring chagnes
