### ISSUE TITLE
Refactor API to make it more testeable.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#62]
**Feature description**

Is a bit hard to write tests with the current library API.

**Is your feature request related to a problem? Please describe.**
Just write tests as requested:
https://github.com/skycoin/hardware-wallet-go/pull/50#pullrequestreview-213769530

**Describe the solution you'd like**
An interface based implementation in the lib.

**Describe alternatives you've considered**
An interface based implementation in the lib.
Or write complex integration tests to tests local functionalities.

**Additional context**
https://github.com/skycoin/hardware-wallet-go/pull/50#pullrequestreview-213769530

**Possible implementation**
Just create some interface to encapsulate functionality

**Comment by therealssj** [comment]
@stdevAlDen the lib already has an interface

**Comment by stdevAlDen** [comment]
> @stdevAlDen the lib already has an interface

But I need a bit more to make easy the use of mock objects an write unit tests, I currently have the changes in my laptop, are you agree to let me submit it and send you a link for review?

**Comment by olemis** [comment]
> @stdevAlDen the lib already has an interface

I was under the impression that it had some ... 

> Its missing the Entropy functions though as for some reason the proto files didnt have it before

@therealssj these should be added in #50 , pending from merge as it needs tests

**Comment by olemis** [comment]
> > @stdevAlDen the lib already has an interface
> 
> But I need a bit more to make easy the use of mock objects an write unit tests, I currently have the changes in my laptop, are you agree to let me submit it and send you a link for review?

Sure upload and create a new PR for us to review .

**Comment by stdevAlDen** [comment]
@olemis & @therealssj https://github.com/skycoin/hardware-wallet-go/pull/63
It's great if we can have tests [here](https://github.com/skycoin/hardware-wallet-go/pull/50#pullrequestreview-213769530)

https://github.com/skycoin/hardware-wallet-go/pull/50/files#diff-e74c5dbf5b6565d473a1d8b1efd4df53R306
This is a example point in where I want to write unit(not integration) tests.

**Comment by olemis** [comment]
> @olemis & @therealssj #63
> It's great if we can have tests [here](https://github.com/skycoin/hardware-wallet-go/pull/50#pullrequestreview-213769530)
> 

maybe I'd have preferred to fix them in that PR ... /me reviewing #63
