### ISSUE TITLE
dep broken

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#65]
**Describe the bug**
dep does not work as its trying to add `github.com/google/protobuf`

**Environment information:**

- OS: any

**Steps to Reproduce**
`make dep`

**Actual behavior**
Error `subpackage github.com/google/protobuf does not contain usable Go code`

**Expected behavior**
no error

**Additional context**
Renamed import: https://github.com/skycoin/hardware-wallet-protob/blob/master/Makefile#L96

**Possible implementation**
Change import to `github.com/skycoin/hardware-wallet-go/src/device-wallet/messages/go/google/protobuf` so we do not have to vendor `github.com/google/protobuf`.

can be done using something like `sed` as in https://github.com/skycoin/hardware-wallet-protob/blob/master/Makefile#L96

**Comment by stdevAlDen** [comment]
An alternative could be to send the prefix of import path as an argument, since it can be used in different projects than hardware-wallet-go
