### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#69]
**Describe the bug**
Unable to update firmware using the cli

**Environment information:**

- OS: MacOS
- Platform: Darwin 18.5.0 x86_64
- Firmware Version: 1.7.0 

**Steps to Reproduce**
1. Start wallet in bootloader mode 
![image](https://user-images.githubusercontent.com/8619106/54483482-a354d800-4879-11e9-84e3-47f6331b078b.png)

2. Use cli to update firmware
`skycoin-hw-cli firmwareUpdate -f skycoin.bin`

This outputs the following error: 
```
File : skycoin.bin
Hash: afb6221d65733725fdb87fee95ee9fe0731e7d2b3a78146c81774bd1d8f0c02a
[2019-03-16T21:56:06+05:30] INFO [device-wallet]: hidapi: failed to open device
[2019-03-16T21:56:06+05:30] INFO [device-wallet]: hidapi: failed to open device
[2019-03-16T21:56:06+05:30] INFO [device-wallet]: hidapi: failed to open device
[2019-03-16T21:56:06+05:30] ERROR [skycoin-hw-cli]: No device connected
```

**Actual behavior**
Failure in updating firmware

**Expected behavior**
Firmware update

**Comment by stdevAlDen** [comment]
The same for SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux.

A good starting point to find the bug can be here:

https://github.com/skycoin/hardware-wallet-go/blob/master/src/device-wallet/helper.go#L68-L98

Check for yourself pls.

**Comment by therealssj** [comment]
Seems there is more as I can not even run integration tests

**Comment by therealssj** [comment]
The issue arises from the fact that while the device is executing a command you cannot call `getDevice`.
When we switched to interfaces we started calling `getDevice` instead of passing around a device instance

**Comment by stdevAlDen** [comment]
> The issue arises from the fact that while the device is executing a command you cannot call `getDevice`.
> When we switched to interfaces we started calling `getDevice` instead of passing around a device instance

This is a workflow example of the problem:
- Try to get(open) the device [here](https://github.com/skycoin/hardware-wallet-go/blob/1b66019aa9e3535390954657de4aea2ba7cff967/src/device-wallet/device-wallet.go#L227)
- Call [`initialize`](https://github.com/skycoin/hardware-wallet-go/blob/1b66019aa9e3535390954657de4aea2ba7cff967/src/device-wallet/device-wallet.go#L233)
- Try to ge([open](https://github.com/skycoin/hardware-wallet-go/blob/master/src/device-wallet/helper.go#L133)) the device again.

Right @therealssj ?

**Comment by therealssj** [comment]
@stdevAlDen yes

**Comment by stdevAlDen** [comment]
> @stdevAlDen yes

@therealssj consider making a unit test like this:
```go
func (suite *devicerSuit) TestFirmwareUpdateShouldMakeASingleCallForGetDevice() {
	// NOTE Giving
	driverMock := &mocks.DeviceDriver{}
	driverMock.On("GetDevice").Return(&testHelperCloseableBuffer{}, nil)
	device := Device{driverMock}

	// NOTE When
	err := device.FirmwareUpload()

	// NOTE Assert
	suite.Nil(err)
	driverMock.AssertNumberOfCalls(suite.T(), "GetDevice", 1)
	mock.AssertExpectationsForObjects(suite.T(), driverMock)
}
```

**Comment by therealssj** [comment]
The error is not in firmware upload.
It's just how the firmware works so we have implemented it wrong.
I get same error when calling some other functions too. 

I have the fix already but waiting for https://github.com/skycoin/hardware-wallet-go/pull/70 coz I would have to revise otherwise

**Comment by stdevAlDen** [comment]
> functions

Oh I see, it's not related to funtion that call initializae like `Wipe`, `FirmwareUpload`, `Backup`...?

**Comment by stdevAlDen** [comment]
> The error is not in firmware upload.
> It's just how the firmware works so we have implemented it wrong.
> I get same error when calling some other functions too.
> 
> I have the fix already but waiting for #70 coz I would have to rebase otherwise

@therealssj can you pls make a push with the changes? I need this feature to be ok for my today work, if you have it working and I can make a `git checkout` to your branch it's great for me :ok_hand:

**Comment by therealssj** [comment]
@stdevAlDen https://github.com/skycoin/hardware-wallet-go/tree/fix-deviceget-error

**Comment by olemis** [comment]
> @stdevAlDen https://github.com/skycoin/hardware-wallet-go/tree/fix-deviceget-error

@therealssj could you pls submit a PR for this ? thnx in advance
