### ISSUE TITLE
Add emulator button press function

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#75]
**Feature description**
Add function to simulate a emulator button press.

**Is your feature request related to a problem? Please describe.**
Required for #68 

**Describe the solution you'd like**
A function to send a udp message to emulator with the format `[0, 1, 2, 3, 4, type ]`, where type can be:

0 => press the left button
1 => press the right button
2 => press both

Example: `[0, 1, 2, 3, 4, 0 ]` for left

**Comment by olemis** [comment]
Similar to [PR #71 for hw-js library](https://github.com/skycoin/hardware-wallet-js/pull/71/files).
