### ISSUE TITLE
Add check to get wallet by skycoinfoundation

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#94]
**Describe the bug**
`GetDevice` should check for manufacturer as `SkycoinFoundation` similar to the js lib

use manufacturer or its equivalent field

**Actual behavior**
Check for manufacturer == `SkycoinFoundation` 

**Expected behavior**
return device only if its by `SkycoinFoundation`

**Possible Implementation**
Check how js lib does it

**Comment by olemis** [comment]
@stdevAlDen I see Travis is failing . Any progress on this ?

**Comment by stdevAlDen** [comment]
> @stdevAlDen I see Travis is failing . Any progress on this ?

@olemis none, I feel a bit confused as the builds for the same refs are working in the pr https://github.com/skycoin/hardware-wallet-go/pull/101
